project:
  type: website
  output-dir: docs

website:
  title: "Isoform Analyses with the EZbakR-suite"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - href: fastq2EZbakR.qmd
        text: fastq2EZbakR
      - href: EZbakR.qmd
        text: EZbakR

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

